---
title: "Project Information"
---

The purpose of this website is to serve as an interactive exploratory analysis to demonstrate the evolution of statistics over time, specifically in regards to "hot topics" used in research. Here you will find plots depicting the distribution of keywords, trends in the number of collaborators over time, as well as the number of citations per paper.

Data were gathered from the Journal of the American Statistical Association <a href="http://amstat.tandfonline.com/loi/uasa20">(JASA)</a> and compiled into one comprehensive dataset that was used in the analysis.

### Data access

The project is located inside our GitHub <a href="https://github.com/angelgar/StatisticsHotTopics">repository</a>. Inside this repository includes an "analysis" folder, which further includes our <a href="https://github.com/angelgar/StatisticsHotTopics/tree/master/analysis/data">data</a> folder. The final dataset is named "jasa_articles_dataset_complete" and can be found <a href="https://github.com/angelgar/StatisticsHotTopics/blob/master/analysis/data/jasa_articles_dataset_complete.csv">here</a>.

## Initial questions

The main question of interest is to undertand if/how keywords used in the titles of JASA-published papers have evolved over time, and when certain topcs arose to be of interest in research. While scraping the data and further investigating the JASA website, we came up with other questions, such as how do certain keywords affect the number of citations, and how has the average number of authors changed over time, and what is the most common word in titles for each year?

## Data

We scrapped this data from the Journal of the American Statistical Association website. We used the "rvest" package to download the data from the internet and the the "SelectorGadget" tool to find the correct CSS selectors. We first obtained the issue number, chapter and publication year. With this information, we were able to access the issue-specific site and scrapped the tile, number of views and number of citations for each of these articles. Furthermore, we accessed the individual article's website to scrap the list of authors for each author. 

We started the data cleaning process by eliminating those entries in our dataset that were not statistical articles. These included all those entries in the "title" variable that contained words such as "Comment", "Book Review", "Correction", "Editorial". 

We proceeded to generate two new dataframes for the purpose of convenience when creating plots. In the dataframe "jasa_articles", we split the author column so that entries of author_1 to author_19 columns contain only one author. We also added an id column, in order to make identifying articles convenient from here on forward. 

For the dataframe, "jasa_rm.stopwords", we unnest the "title" column; the "word" column now contains each of the words from its respective title. Also, note that we kept all hyphenated words as one word (we wanted to keep the word "p-value" as one). We also joined jasa_articles and jasa_rm_stopwords so that we have a column for each unnested word and its corresponding title column. After some analysis, some words (for example, prepositions, conjunctions, articles, etc.) were found to be most frequent by year, but were uninformative, so we removed them. 

Lastly, we chose some words (contained in the "words" vector) manually that we wanted to do some analysis on. We chose some words that did not necessarily appear most frequently for each year, but more interesting. It should be noted that "bayes" would be matched to "bayes" and "bayesian", "estimate" would be matched to "estimate" and "estimate", "parametric" would be matched to "nonparametric", "parametric" and "semiparametric" and "sampl" would be matched to "sample" and "sampling". We created a new column in "jasa_rm_stopwords" that indicated what the words were matched to, because we would like to group similar words together, as explained above. The final dataframe was written as a csv file and saved into our data folder.

## Exploratory analysis

After data were cleaned, we created visualization plots to illustrate our questions of interest. Once data were in a readable format for plot creation, minimal steps were needed between data cleaning and plot creation. Early on in the evolution of our project, we determined the types of questions we wanted to ask, and how to appropriately answer these questions visually. We concluded on representing our output through the use of four plots, in addition to one on the landing page of our website.

The landing page of our website is a word cloud to illustrate the frequency of the top 100 words used, with larger words indicating greater frequency. This plot serves as an introduction/opening to the additional plots presented on a flexdashboard. 

#### The additional plots include: 

#### (1) Top word per year

#### (2) Trend of keywords over time

#### (3) Number of collaborators per article per year

#### (4) Number of citations per keyword. 

## Discussion

Since our analysis relied on visual representations of data scraped form JASA, no formal statistical conclusions can be made. However, it is interesting to examine trends that appeared as a result of looking at the relationship between statistical "hot topics." Major trends are noted in the remainder of the discussion. From the first plot, we can see that "statistics" and "statistical" dominated word proportion until the 1960s, when words such as "estimation", "models", and "data" began to appear. It is imporant to note here that proportions of key words likely decreased over time because as more papers were published into the 1940s, there became more vairability in the titles. From the second plot, we can see that only "statistic" has remained relatively steady over time, and there was a spike in "p-value" after the year 2000, consistent with the growing attention p-values are getting. The third plot shows a clear positive trend in the number of authors cited, illustrating an increase in collaboration on statistical papers. It will be interesting to note if this trend continues to increase and/or ever reaches a plateau or decrease in the trend. From the fourth plot we know that "estimate", "model", and "regression" generate the greatest number of citations and "p-value", "clinical", and "bootstrap" generate the fewest number of citations.

For future analysis, it would be interesting to examine the relationship between tagged phrases by authors and number of citations, trends in the words over time, etc. Additionally, it would be useful to follow the project with a formal statistical analysis of when certain words increased in prevalence, not only in titles but in words used throughout the papers.

