---
title: "Evolution of Statistics 'Hot Topics'"
---

```{r, load data, echo = FALSE, message = FALSE, warning = FALSE}

library(readr)
library(dplyr)
library(stringr)
library(tidyverse)
library(tidytext)
library(janitor)
library(ggplot2)
library(wordcloud)
library(RColorBrewer)
library(knitr)

data("stop_words")

jasa_articles = read_csv("./analysis/jasa_articles_dataset_complete.csv") %>%
  clean_names() %>% 
  separate(authors, into = c("author1", "author19"), sep = " & ") %>% 
  separate(author1, into = paste("author", 1:18), sep = ", ") %>% 
  unnest_tokens(word, title)

jasa_articles = anti_join(jasa_articles, stop_words)
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
word_map_data <- jasa_articles %>% 
  count(word, sort = TRUE) %>%
  top_n(200)
```

```{r, echo = FALSE, message = FALSE, warning = FALSE, out.width = '250%'}
wordcloud(words = word_map_data$word, freq = word_map_data$n, min.freq = 50,
          max.words = 100, random.order = FALSE, rot.per = 0.35, 
          colors = brewer.pal(8, "Dark2"))
```

