---
title: "Final Report"
author: "Hyewon Choi, Angel Garcia de la Garza, Soo Hyun Kim, Rebecca Venetianer"
output: html_document
---

### Data access
The project is located inside our GitHub <a href="https://github.com/angelgar/StatisticsHotTopics">repository</a>. Inside this repository includes an "analysis" folder, which further includes our <a href="https://github.com/angelgar/StatisticsHotTopics/tree/master/analysis/data">data</a> folder. The final dataset is named "jasa_articles_dataset_complete" and can be found <a href="https://github.com/angelgar/StatisticsHotTopics/blob/master/analysis/data/jasa_articles_dataset_complete.csv">here</a>.

## Motivation
The goal of our analysis is to understand the evolution of statistics over time, specifically in regards to "hot topics" used in research. We analyzed the titles of articles published in the Journal of the American Statistical Association (JASA) since 1888, as well as other factors such as authors, number of citations, etc. We used data gathered to create exploratory plots regarding the aforementioned factors. Specifically, we then found correlations of specific "hot topics" with article impact as measured by article views and citations.

## Related work
When beginning this project, we struggled to come to a conclusion about the type of data we wanted to analyze and represent visually. We agreed on the importance of creating a comprehensive visual for readers to explore, but had a plethora of ideas about the topic. After exploring datasets on happiness, crime rates, and general health data from NHANES, we switched gears and decided to create our own dataset using published papers from JASA. Each group members comes with various interests in health, data analytics, data visualization, etc. Our combined interest in statistics makes the exploration of statistical hot topics over time a perfect fit.

@ Angel talk about the seminar you went to if you want.

## Initial questions
The main question of interest is to undertand if/how keywords used in the titles of JASA-published papers have evolved over time, and when certain topcs arose to be of interest in research. While scraping the data and further investigating the JASA website, we came up with other questions, such as how do certain keywords affect the number of citations, and how has the average number of authors changed over time, and what is the most common word in titles for each year?

## Data

We scrapped this data from the Journal of the American Statistical Association website. We used the "rvest" package to download the data from the internet and the the "SelectorGadget" tool to find the correct CSS selectors. We first obtained the issue number, chapter and publication year. With this information, we were able to access the issue-specific site and scrapped the tile, number of views and number of citations for each of these articles. Furthermore, we accessed the individual article's website to scrap the list of authors for each author. 

We started the data cleaning process by eliminating those entries in our dataset that were not statistical articles. These included all those entries labeled as "Comment", "Book Review", "Correction", "Editorial". 

@Soohyun

## Exploratory analysis

After data were cleaned, we created visualization plots to illustrate our questions of interest. Once data were in a readable format for plot creation, minimal steps were needed between data cleaning and plot creation. Early on in the evolution of our project, we determined the types of questions we wanted to ask, and how to appropriately answer these questions visually. We concluded on representing our output through the use of four plots, in addition to one on the landing page of our website.

The landing page of our website is a word cloud to illustrate the frequency of the top 100 words used, with larger words indicating greater frequency. This plot serves as an introduction/opening to the additional plots presented on a flexdashboard. The additional plots include: (1) top word per year, (2) trend of keywords over time, (3) number of collaborators per article per year, (4) number of citations per keyword. For the first plot, we created a barplot with "year" on the x-axis and "proportion" on the y-axis. "Proportion" represents the proportion of times the most common word for the year of interest appears in a title, out of the total number of papers published for that year.  For this plot, we removed stop words and other non-useful words from being the most common, allowing only relevant words such as "model" to appear as the most frequent. Without doing so, the plot would produce data showing words such as "the" and "and" as the most frequent.

For the second plot, we focused on ten keywords and created a spaghetti plot with "year" on the x-axis and and "proportion" on the y-axis. These ten keywords were chosen as words that all group members thought would be important to examine the trends of. This plot allowed us to visually demostrate increasing and decreasing trends of various words over time. "Proportion" in this plot corresponds to the same ratio method used for the previous plot. 

For the third plot, we created a dot plot with "year" on the x-axis and "count" on the y-axis, with "count" referring to the mean number of collaborators per article per year. The goal of this was to understand trends in collaboration over time, with the hypothesis that collaboration has increased, and therefore the mean number of collaborators per article per year has also increased.. 

Similarly to the third plot, we created the fourth plot to determine a visual relationship between "number of citations" and "keyword".

## Discussion
